data:
    name: 'ScanNet'
    class_name: 'Scannet'
    gt_pairs: 'ScanNet/scannet_test_pairs_with_gt.txt'
    images_path:  'ScanNet'
    resize: [480, 640]
    epi_thrsehold: 0.0005
    shuffle: false
    max_length: -1
    batch_size: 1
matcher:
  method: "mnn"
  top_k: 20000
  dist_thresh: null
  max_ratio: null
  temperature: 0.1
  cross_check: True
  ransac_thresh: 0.5
  bias: 9.0
